#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

. ../common.sh

function createTmpDir {
    mktemp -d -t tmp.XXXXXXXXXX
}

readonly TMPDIR=$(createTmpDir)
function cleanup {
  rm -rf "$TMPDIR"
}
trap cleanup EXIT


# ######################################################################

info "Shift collumns"



