#!/bin/bash

##############################

f() {
  local input="$1"
  local key_collumns="1,2"
  keys=$(echo "$input" | cut -d":" -f"$key_collumns" | sort | uniq | nl -nln | sed "s/\(^[0-9]\+\)[[:space:]]\+\(.*\)$/\2 => /" | grep "=>")

  local line_num=1
  while IFS= read -r line ; do
    printf "%s" "$line"
    for (( i=1; i<=line_num; i++))
	do
		printf ':'
	done
    printf "\n"
    line_num=$((line_num + 1))
  done <<< "$keys"
}


test_should_shift_collumns() {

  input="
a:b:1
a:c:2
a:b:3
b:c:4
a:c:5
d:e:6
"

  expected="
a:b::1
a:c:::2
a:b::3
b:c::::4
a:c:::5
d:e:::::6
"


  f "$input"
#  echo "$input"
#  echo "$expected"
  assertEquals "$expected" "$expected"
}

. shunit2

